export const dataSourceSRF = [
    {
      community: "SE",
      key: "1",
      name: "Mike",
      avg: "Lost Price",
      gm: "35.00",
      spec: "Rental Income",
      backlog: "2.400",
      ofUnits: "",
      plan: "STARTS",
      1 : "",
      total: 0
    },
    {
        community: "Savannah Estates",
        key: "1",
        name: "Mike",
        avg: "Lost Cost",
        gm: "35.00",
        spec: "Rental Income",
        backlog: "2.400",
        ofUnits: "",
        plan: "FINISH",
        1 : "",
        total: 0
      },
      {
        community: "",
        key: "1",
        name: "Mike",
        avg: "Cash Out",
        gm: "35.00",
        spec: "Rental Income",
        backlog: "2.400",
        ofUnits: "",
        plan: "RENTS",
        1 : "",
        total: 0
      },
      {
        community: "SS",
        key: "1",
        name: "Mike",
        avg: "Lost Price",
        gm: "35.00",
        spec: "Rental Income",
        backlog: "2.400",
        ofUnits: "",
        plan: "STARTS",
        1 : "",
        total: 0
      },
      {
          community: "2nd St Commons Rental",
          key: "1",
          name: "Mike",
          avg: "Lost Cost",
          gm: "35.00",
          spec: "Rental Income",
          backlog: "2.400",
          ofUnits: "",
          plan: "FINISH",
          1 : "",
          total: 0
        },
        {
          community: "",
          key: "1",
          name: "Mike",
          avg: "Cash Out",
          gm: "35.00",
          spec: "Rental Income",
          backlog: "2.400",
          ofUnits: "",
          plan: "RENTS",
          1 : "",
          total: 0
        },
        {
            community: "PS/SE/SN/PP/HT",
            key: "1",
            name: "Mike",
            avg: "Lost Price",
            gm: "35.00",
            spec: "Rental Income",
            backlog: "2.400",
            ofUnits: "",
            plan: "STARTS",
            1 : "",
            total: 0
          },
          {
              community: "TBD",
              key: "1",
              name: "Mike",
              avg: "Lost Cost",
              gm: "35.00",
              spec: "Rental Income",
              backlog: "2.400",
              ofUnits: "",
              plan: "FINISH",
              1 : "",
              total: 0
            },
            {
              community: "",
              key: "1",
              name: "Mike",
              avg: "Cash Out",
              gm: "35.00",
              spec: "Rental Income",
              backlog: "2.400",
              ofUnits: "",
              plan: "RENTS",
              1 : "",
              total: 0
            },
    
]